//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public Admin()
        {
            this.Notice = new HashSet<Notice>();
            this.OnlineContest = new HashSet<OnlineContest>();
            this.Problem = new HashSet<Problem>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Sex { get; set; }
        public int Age { get; set; }
        public string QQ { get; set; }
        public string Tel { get; set; }
        public short State { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual ICollection<Notice> Notice { get; set; }
        public virtual ICollection<OnlineContest> OnlineContest { get; set; }
        public virtual ICollection<Problem> Problem { get; set; }
    }
}
