//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discuss
    {
        public Discuss()
        {
            this.Answer = new HashSet<Answer>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public System.DateTime QuestionTime { get; set; }
        public string Title { get; set; }
        public string ProblemDescription { get; set; }
    
        public virtual ICollection<Answer> Answer { get; set; }
        public virtual User User { get; set; }
    }
}
