//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public int ID { get; set; }
        public string Describe { get; set; }
        public short State { get; set; }
        public int AdminID { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
