//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProblemType
    {
        public ProblemType()
        {
            this.Problem = new HashSet<Problem>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
        public Nullable<int> ProNumber { get; set; }
    
        public virtual ICollection<Problem> Problem { get; set; }
    }
}
