//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PWCEntities : DbContext
    {
        public PWCEntities()
            : base("name=PWCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admin { get; set; }
        public DbSet<Answer> Answer { get; set; }
        public DbSet<Discuss> Discuss { get; set; }
        public DbSet<Notice> Notice { get; set; }
        public DbSet<OnlineContest> OnlineContest { get; set; }
        public DbSet<Problem> Problem { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<Record> Record { get; set; }
        public DbSet<RecordUser> RecordUser { get; set; }
        public DbSet<OCProblem> OCProblem { get; set; }
        public DbSet<Result> Result { get; set; }
        public DbSet<ProblemType> ProblemType { get; set; }
        public DbSet<UserProblem> UserProblem { get; set; }
        public DbSet<TestData> TestData { get; set; }
    }
}
