//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public Record()
        {
            this.RecordUser = new HashSet<RecordUser>();
        }
    
        public int ID { get; set; }
        public System.DateTime TodayDate { get; set; }
        public int LoginNumber { get; set; }
        public int AllAnswerPro { get; set; }
    
        public virtual ICollection<RecordUser> RecordUser { get; set; }
    }
}
