//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Answer = new HashSet<Answer>();
            this.Discuss = new HashSet<Discuss>();
            this.RecordUser = new HashSet<RecordUser>();
            this.UserProblem = new HashSet<UserProblem>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Sex { get; set; }
        public int Age { get; set; }
        public string QQ { get; set; }
        public string Tel { get; set; }
        public string Introduce { get; set; }
        public System.DateTime CreationDate { get; set; }
        public short State { get; set; }
        public int Problems { get; set; }
        public int Accepteds { get; set; }
    
        public virtual ICollection<Answer> Answer { get; set; }
        public virtual ICollection<Discuss> Discuss { get; set; }
        public virtual ICollection<RecordUser> RecordUser { get; set; }
        public virtual ICollection<UserProblem> UserProblem { get; set; }
    }
}
